add wave -position insertpoint  \
sim:/tb_channel_equalizer/reset \
sim:/tb_channel_equalizer/clock \
sim:/tb_channel_equalizer/io_reference_in_real \
sim:/tb_channel_equalizer/io_reference_in_imag \
sim:/tb_channel_equalizer/io_reference_addr \
sim:/tb_channel_equalizer/io_reference_write_en \
sim:/tb_channel_equalizer/channel_equalizer/memblock/mem_real \
sim:/tb_channel_equalizer/channel_equalizer/memblock/mem_imag \
sim:/tb_channel_equalizer/channel_equalizer/memblock/io_write_addr \
sim:/tb_channel_equalizer/channel_equalizer/memblock/io_write_val_real \
sim:/tb_channel_equalizer/channel_equalizer/memblock/io_write_val_imag \
sim:/tb_channel_equalizer/channel_equalizer/memblock_1/mem_real \
sim:/tb_channel_equalizer/channel_equalizer/memblock_1/mem_imag \
sim:/tb_channel_equalizer/channel_equalizer/memblock_1/io_write_en \
sim:/tb_channel_equalizer/channel_equalizer/memblock_1/io_write_addr \
sim:/tb_channel_equalizer/channel_equalizer/io_estimate_sync \
sim:/tb_channel_equalizer/channel_equalizer/io_estimate_user_index \
sim:/tb_channel_equalizer/channel_equalizer/equalize_address_counter \
sim:/tb_channel_equalizer/channel_equalizer/estimate_address_counter \
sim:/tb_channel_equalizer/channel_equalizer/complex_reciprocal/io_N_real \
sim:/tb_channel_equalizer/channel_equalizer/complex_reciprocal/io_N_imag \
sim:/tb_channel_equalizer/channel_equalizer/complex_reciprocal/io_D_real \
sim:/tb_channel_equalizer/channel_equalizer/complex_reciprocal/io_D_imag \
sim:/tb_channel_equalizer/channel_equalizer/edge_detector_5/io_rising \
sim:/tb_channel_equalizer/channel_equalizer/complex_reciprocal/io_Q_real \
sim:/tb_channel_equalizer/channel_equalizer/complex_reciprocal/io_Q_imag \
sim:/tb_channel_equalizer/channel_equalizer/r_estimate_done \
sim:/tb_channel_equalizer/channel_equalizer/r_estimate_format \
sim:/tb_channel_equalizer/channel_equalizer/r_estimate_done_flag \
sim:/tb_channel_equalizer/channel_equalizer/io_estimate_write_en \
sim:/tb_channel_equalizer/channel_equalizer/io_estimate_addr \
sim:/tb_channel_equalizer/io_A_real \
sim:/tb_channel_equalizer/io_A_imag \
sim:/tb_channel_equalizer/io_estimate_sync \
sim:/tb_channel_equalizer/io_equalize_sync \
sim:/tb_channel_equalizer/channel_equalizer/r_A_real \
sim:/tb_channel_equalizer/channel_equalizer/r_A_imag \
sim:/tb_channel_equalizer/channel_equalizer/r_estimate_sync \
sim:/tb_channel_equalizer/channel_equalizer/r_equalize_sync \
sim:/tb_channel_equalizer/io_estimate_read_en \
sim:/tb_channel_equalizer/io_estimate_addr \
sim:/tb_channel_equalizer/io_estimate_out_0_real \
sim:/tb_channel_equalizer/io_estimate_out_0_imag \
sim:/tb_channel_equalizer/channel_equalizer/memblock_1/mem_real \
sim:/tb_channel_equalizer/channel_equalizer/memblock_1/mem_imag \
sim:/tb_channel_equalizer/channel_equalizer/memblock_2/mem_real \
sim:/tb_channel_equalizer/channel_equalizer/memblock_2/mem_imag \
sim:/tb_channel_equalizer/channel_equalizer/memblock_3/mem_real \
sim:/tb_channel_equalizer/channel_equalizer/memblock_3/mem_imag \
sim:/tb_channel_equalizer/channel_equalizer/memblock_4/mem_real \
sim:/tb_channel_equalizer/channel_equalizer/memblock_4/mem_imag \
sim:/tb_channel_equalizer/channel_equalizer/memblock_5/mem_real \
sim:/tb_channel_equalizer/channel_equalizer/memblock_5/mem_imag \
sim:/tb_channel_equalizer/channel_equalizer/memblock_6/mem_real \
sim:/tb_channel_equalizer/channel_equalizer/memblock_6/mem_imag \
sim:/tb_channel_equalizer/channel_equalizer/memblock_7/mem_real \
sim:/tb_channel_equalizer/channel_equalizer/memblock_7/mem_imag \
sim:/tb_channel_equalizer/channel_equalizer/memblock_8/mem_real \
sim:/tb_channel_equalizer/channel_equalizer/memblock_8/mem_imag \
sim:/tb_channel_equalizer/channel_equalizer/memblock_9/mem_real \
sim:/tb_channel_equalizer/channel_equalizer/memblock_9/mem_imag \
sim:/tb_channel_equalizer/channel_equalizer/memblock_10/mem_real \
sim:/tb_channel_equalizer/channel_equalizer/memblock_10/mem_imag \
sim:/tb_channel_equalizer/channel_equalizer/memblock_11/mem_real \
sim:/tb_channel_equalizer/channel_equalizer/memblock_11/mem_imag \
sim:/tb_channel_equalizer/channel_equalizer/memblock_12/mem_real \
sim:/tb_channel_equalizer/channel_equalizer/memblock_12/mem_imag \
sim:/tb_channel_equalizer/channel_equalizer/memblock_13/mem_real \
sim:/tb_channel_equalizer/channel_equalizer/memblock_13/mem_imag \
sim:/tb_channel_equalizer/channel_equalizer/memblock_14/mem_real \
sim:/tb_channel_equalizer/channel_equalizer/memblock_14/mem_imag \
sim:/tb_channel_equalizer/channel_equalizer/memblock_15/mem_real \
sim:/tb_channel_equalizer/channel_equalizer/memblock_15/mem_imag \
sim:/tb_channel_equalizer/channel_equalizer/memblock_16/mem_real \
sim:/tb_channel_equalizer/channel_equalizer/memblock_16/mem_imag \
sim:/tb_channel_equalizer/io_Z_0_real \
sim:/tb_channel_equalizer/io_Z_0_imag \
sim:/tb_channel_equalizer/io_Z_1_real \
sim:/tb_channel_equalizer/io_Z_1_imag \
sim:/tb_channel_equalizer/io_Z_2_real \
sim:/tb_channel_equalizer/io_Z_2_imag \
sim:/tb_channel_equalizer/io_Z_3_real \
sim:/tb_channel_equalizer/io_Z_3_imag \
sim:/tb_channel_equalizer/io_Z_4_real \
sim:/tb_channel_equalizer/io_Z_4_imag \
sim:/tb_channel_equalizer/io_Z_5_real \
sim:/tb_channel_equalizer/io_Z_5_imag \
sim:/tb_channel_equalizer/io_Z_6_real \
sim:/tb_channel_equalizer/io_Z_6_imag \
sim:/tb_channel_equalizer/io_Z_7_real \
sim:/tb_channel_equalizer/io_Z_7_imag \
sim:/tb_channel_equalizer/io_Z_8_real \
sim:/tb_channel_equalizer/io_Z_8_imag \
sim:/tb_channel_equalizer/io_Z_9_real \
sim:/tb_channel_equalizer/io_Z_9_imag \
sim:/tb_channel_equalizer/io_Z_10_real \
sim:/tb_channel_equalizer/io_Z_10_imag \
sim:/tb_channel_equalizer/io_Z_11_real \
sim:/tb_channel_equalizer/io_Z_11_imag \
sim:/tb_channel_equalizer/io_Z_12_real \
sim:/tb_channel_equalizer/io_Z_12_imag \
sim:/tb_channel_equalizer/io_Z_13_real \
sim:/tb_channel_equalizer/io_Z_13_imag \
sim:/tb_channel_equalizer/io_Z_14_real \
sim:/tb_channel_equalizer/io_Z_14_imag \
sim:/tb_channel_equalizer/io_Z_15_real \
sim:/tb_channel_equalizer/io_Z_15_imag \

run -all

